import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { getPosts } from '../lib/api';
import Link from 'next/link';
import Layout from '../components/layout';
import Hero from '../components/hero';
import AboutUs from '../components/about-us';
import Tools from '../components/tools';

//export async function getStaticProps(){
//  let posts = await getPosts();
//  return {
//    props: {
//      posts
//    }
//  }
//}

export const siteTitle = "Dharmic Pursut";

export default function Home({ posts }) {
  return (
    <Layout>
        <Head>
          <title>{siteTitle}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
        </Head>

        {console.log(posts)}

        <Hero />
        <AboutUs />
        <Tools />
        <div className={styles.main}>
          {/*{
            posts.map((post,index) => (
              <div key={index}>

                <Link href={`/posts/${post.node.id}`}>
                <a style={{color:'blue'}}>{post.node.title}</a>
                </Link>
                
                <div dangerouslySetInnerHTML={{__html:post.node.content}} />

                <p>By {post.node.author.node.name}</p>
              </div>
            ))
          }*/}
        </div>
    </Layout>
  )
}
